### ISSUE TITLE
進入MainReplyPage回覆貼文成功。 會出現失敗的訊息

### ISSUE THREAD

**Issue by s339428326** [s339428326/AlphaCamp-Twitter#57]
需要找一下是不是判斷邏輯錯誤，或是其他原因造成的感謝！

**Comment by LucySoCute** [comment]
我剛剛測試，dev tool 顯示錯誤喔，說你加的   setTweetReplyCount((prevValue) => prevValue + 1); 不是一個 function。然後我把它移除後，就可以顯示推文成功～
然後我剛剛看 MainReplyModal 裡  console.log(typeof setTweetReplyCount) 的話會顯示 undefined

**Comment by s339428326** [comment]
`
  if (setTweetReplyCount) {
          setTweetReplyCount((prevValue) => prevValue + 1);
}
`
這段程式會去更新Tweet 回覆數量不過我加了判斷是先做debug感謝
